# SF Rent Board Housing Inventory

https://data.sfgov.org/Housing-and-Buildings/Rent-Board-Housing-Inventory/gdc7-dmcn/about_data

In [55]:
import pandas

In [56]:
# see what we're dealing with
pandas.set_option('display.max_columns', None)
inventory_df = pandas.read_csv('data/sf_rent/Rent_Board_Housing_Inventory_20250314.csv')
inventory_df

,unique_id,block_num,unit_count,case_type_name,submission_year,block_address,occupancy_type,occupancy_or_vacancy_date,occupancy_or_vacancy_date_year,bedroom_count,bathroom_count,square_footage,monthly_rent,base_rent_includes_water,base_rent_includes_natural_gas,base_rent_includes_electricity,base_rent_includes_refuse_recycling,base_rent_includes_other_utilities,past_occupancy,vacancy_date,signature_date,occupancy_or_vacancy_date_history,year_property_built,point,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at
0,-3628485104392603866,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
1,-2826846618703330734,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/02/08,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$250-$500,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
2,-8535828261092955964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
3,-9003118150577022274,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
4,3838177617614172843,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2023/05/03,2023,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186683,-7484992084690087964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
186684,-6165581344280503108,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/02,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
186685,-6469473855511513476,1369,12,Housing Inventory - Unit information (2022),2022,100 Block of 09TH AVE,Vacant,NaN,NaN,One-Bedroom,One bathroom,501-750 Sq.Ft,NaN,N,N,N,N,NaN,NaN,2022/06/21,2022/06/21,NaN,1924.0,POINT (-122.467900457 37.78559791),Inner Richmond,1.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
186686,-391686748792554513,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$751-$1000,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM
186687,-452610934157304139,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/22,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM

In [57]:
"""
The point column are values such as:
POINT (-122.394549329 37.781408195)

Split these up to get the longitude and latitude values in 2 separate columns.
"""
inventory_df[['longitude', 'latitude']] = inventory_df['point']\
    .str.extract(r'POINT \((.*)\)')[0]\
    .str.split(' ', expand=True)

# convert the new columns to numeric
inventory_df['longitude'] = pandas.to_numeric(inventory_df['longitude'])
inventory_df['latitude'] = pandas.to_numeric(inventory_df['latitude'])

inventory_df

,unique_id,block_num,unit_count,case_type_name,submission_year,block_address,occupancy_type,occupancy_or_vacancy_date,occupancy_or_vacancy_date_year,bedroom_count,bathroom_count,square_footage,monthly_rent,base_rent_includes_water,base_rent_includes_natural_gas,base_rent_includes_electricity,base_rent_includes_refuse_recycling,base_rent_includes_other_utilities,past_occupancy,vacancy_date,signature_date,occupancy_or_vacancy_date_history,year_property_built,point,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at,longitude,latitude
0,-3628485104392603866,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
1,-2826846618703330734,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/02/08,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$250-$500,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
2,-8535828261092955964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
3,-9003118150577022274,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
4,3838177617614172843,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2023/05/03,2023,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186683,-7484992084690087964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
186684,-6165581344280503108,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/02,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
186685,-6469473855511513476,1369,12,Housing Inventory - Unit information (2022),2022,100 Block of 09TH AVE,Vacant,NaN,NaN,One-Bedroom,One bathroom,501-750 Sq.Ft,NaN,N,N,N,N,NaN,NaN,2022/06/21,2022/06/21,NaN,1924.0,POINT (-122.467900457 37.78559791),Inner Richmond,1.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.467900,37.785598
186686,-391686748792554513,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$751-$1000,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408
186687,-452610934157304139,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/22,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408

In [58]:
# clean up square footage from 501-750 Sq.Ft to 2 columns of 501 and 750
def extract_square_footage(text):
    if pandas.isna(text):
        return pandas.NA, pandas.NA
    
    # Remove common text patterns and convert to lowercase
    text = str(text).lower().replace('sq.ft', '').replace('sqft', '').replace('ft', '').replace('$', '').strip()
    
    # Handle ranges (e.g. "800-1000" or "800 - 1000")
    if '-' in text:
        parts = text.replace(' ', '').split('-')
        try:
            return float(parts[0]), float(parts[1])
        except:
            return pandas.NA, pandas.NA
    
    # Handle single values
    try:
        value = float(text.replace(',', ''))
        return value, value
    except:
        return pandas.NA, pandas.NA

# Apply the function and create new columns
inventory_df[['min_square_footage', 'max_square_footage']] = inventory_df['square_footage'].apply(
    lambda x: pandas.Series(extract_square_footage(x))
)

inventory_df

,unique_id,block_num,unit_count,case_type_name,submission_year,block_address,occupancy_type,occupancy_or_vacancy_date,occupancy_or_vacancy_date_year,bedroom_count,bathroom_count,square_footage,monthly_rent,base_rent_includes_water,base_rent_includes_natural_gas,base_rent_includes_electricity,base_rent_includes_refuse_recycling,base_rent_includes_other_utilities,past_occupancy,vacancy_date,signature_date,occupancy_or_vacancy_date_history,year_property_built,point,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at,longitude,latitude,min_square_footage,max_square_footage
0,-3628485104392603866,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
1,-2826846618703330734,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/02/08,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$250-$500,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
2,-8535828261092955964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
3,-9003118150577022274,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
4,3838177617614172843,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2023/05/03,2023,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186683,-7484992084690087964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
186684,-6165581344280503108,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/02,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
186685,-6469473855511513476,1369,12,Housing Inventory - Unit information (2022),2022,100 Block of 09TH AVE,Vacant,NaN,NaN,One-Bedroom,One bathroom,501-750 Sq.Ft,NaN,N,N,N,N,NaN,NaN,2022/06/21,2022/06/21,NaN,1924.0,POINT (-122.467900457 37.78559791),Inner Richmond,1.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.467900,37.785598,501.0,750.0
186686,-391686748792554513,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$751-$1000,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0
186687,-452610934157304139,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/22,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0

In [59]:
# clean up monthly rent from $501-$750 to 2 columns with 501, 750
def extract_montly_rent(text):
    if pandas.isna(text):
        return pandas.NA, pandas.NA
    
    # Remove common text patterns and convert to lowercase
    text = str(text).lower().replace('$', '').strip()
    
    # Handle ranges (e.g. "800-1000" or "800 - 1000")
    if '-' in text:
        parts = text.replace(' ', '').split('-')
        try:
            return float(parts[0]), float(parts[1])
        except:
            return pandas.NA, pandas.NA
    
    # Handle single values
    try:
        value = float(text.replace(',', ''))
        return value, value
    except:
        return pandas.NA, pandas.NA

# Apply the function and create new columns
inventory_df[['min_monthly_rent', 'max_monthly_rent']] = inventory_df['monthly_rent'].apply(
    lambda x: pandas.Series(extract_montly_rent(x))
)

inventory_df

,unique_id,block_num,unit_count,case_type_name,submission_year,block_address,occupancy_type,occupancy_or_vacancy_date,occupancy_or_vacancy_date_year,bedroom_count,bathroom_count,square_footage,monthly_rent,base_rent_includes_water,base_rent_includes_natural_gas,base_rent_includes_electricity,base_rent_includes_refuse_recycling,base_rent_includes_other_utilities,past_occupancy,vacancy_date,signature_date,occupancy_or_vacancy_date_history,year_property_built,point,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at,longitude,latitude,min_square_footage,max_square_footage,min_monthly_rent,max_monthly_rent
0,-3628485104392603866,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0
1,-2826846618703330734,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/02/08,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$250-$500,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,250.0,500.0
2,-8535828261092955964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0
3,-9003118150577022274,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0
4,3838177617614172843,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2023/05/03,2023,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186683,-7484992084690087964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0
186684,-6165581344280503108,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/02,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,<NA>,<NA>
186685,-6469473855511513476,1369,12,Housing Inventory - Unit information (2022),2022,100 Block of 09TH AVE,Vacant,NaN,NaN,One-Bedroom,One bathroom,501-750 Sq.Ft,NaN,N,N,N,N,NaN,NaN,2022/06/21,2022/06/21,NaN,1924.0,POINT (-122.467900457 37.78559791),Inner Richmond,1.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.467900,37.785598,501.0,750.0,<NA>,<NA>
186686,-391686748792554513,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$751-$1000,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,751.0,1000.0
186687,-452610934157304139,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/22,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,<NA>,<NA>

In [60]:
# normaize the bedroom count string to a number
def extract_bedroom_count(text):
    if pandas.isna(text):
        return pandas.NA
    
    # cleanup
    text = str(text).lower().strip()

    # map numbers in words to numbers
    word_numbers = {
        'zero': 0,
        'one': 1,
        'two': 2,
        'three': 3,
        'four': 4,
        'five': 5
    }
    for word, number in word_numbers.items():
        text = text.replace(word, str(number))

    # special case for "5+"
    if text == '5+':
        return 6

    # extract only the contigous numbers e.g. "4-bedroom" -> 4, "0ah" -> 0
    number_str = ''
    for c in text:
        if c.isdigit():
            number_str += c
        else:
            break

    # cast to number
    try:
        num_bedrooms = int(number_str)
        if num_bedrooms > 5:
            return 0
        else:
            return num_bedrooms
    except:
        return 0

In [61]:
# sanity check we're converting the bedroom count correctly
for bedrooms in inventory_df['bedroom_count'].unique():
    print(bedrooms, ' -> ', extract_bedroom_count(bedrooms))

Studio  ->  0
Two-Bedroom  ->  2
One-Bedroom  ->  1
Three-Bedroom  ->  3
nan  ->  <NA>
Four-Bedroom  ->  4
5+  ->  6
2  ->  2
1  ->  1
3  ->  3
Two Bedroom  ->  2
0  ->  0
One Bedroom  ->  1
studio  ->  0
Studio (sm)  ->  0
Garage  ->  0
One-bedroom  ->  1
Two-bedroom  ->  2
1 bedroom  ->  1
2 bedroom  ->  2
3 bedroom  ->  3
2 bedroomq  ->  2
1bedroom  ->  1
3bedroom  ->  3
2 bedriin  ->  2
$D$61  ->  0
1 bed  ->  1
2A  ->  2
0A  ->  0
1A  ->  1
0AH  ->  0
Zero -(Studio)  ->  0
Zero-(Studio)  ->  0
Five-Bedroom  ->  5
Vacant  ->  0
1br  ->  1
2brd  ->  2
2br  ->  2

In [62]:
# normalize bathroom count to a number
def extract_bathroom_count(text):
    if pandas.isna(text):
        return pandas.NA
    
    # cleanup
    text = str(text).lower().strip()

    # map numbers in words to numbers
    word_numbers = {
        'one and a half': 1.5,
        'two and a half': 2.5,
        'zero': 0,
        'one': 1,
        'two': 2,
        'three': 3
    }
    for word, number in word_numbers.items():
        text = text.replace(word, str(number))

    # extract the numbers
    number_str = ''
    for c in text:
        if c.isdigit() or c == '.':
            number_str += c
        else:
            break

    # cast to number
    try:
        return float(number_str)
    except:
        return 0

In [63]:
# make sure we're doing it properly
for bedrooms in inventory_df['bathroom_count'].unique():
    print(bedrooms, ' -> ', extract_bathroom_count(bedrooms))

Shared bathroom facilities with other units  ->  0
One bathroom  ->  1.0
Two bathrooms  ->  2.0
nan  ->  <NA>
One and a half bathrooms  ->  1.5
Three bathrooms or more  ->  3.0
Two and a half bathrooms  ->  2.5
One-Bathroom  ->  1.0
1.00  ->  1.0
2.00  ->  2.0
1  ->  1.0
2  ->  2.0
2.5  ->  2.5
One Bathroom  ->  1.0
Two Bathroom  ->  2.0
One and a Half Bathrooms  ->  1.5
shared bathroom facilities with other units  ->  0
2 bathroom  ->  2.0
1 bathroom  ->  1.0
2 batroom  ->  2.0
1 bedroom  ->  1.0
2 bedroom  ->  2.0
1bathroom  ->  1.0
2  bathroom  ->  2.0
Two-Bathroom  ->  2.0
E3  ->  0
Two bathroom  ->  2.0
One and a half bathdrooms  ->  1.5

In [64]:
inventory_df.rename(columns={
    'bedroom_count': 'bedrooms_raw',
    'bathroom_count': 'bathrooms_raw'
}, inplace=True)

inventory_df['bedrooms'] = inventory_df['bedrooms_raw'].apply(extract_bedroom_count)
inventory_df['bathrooms'] = inventory_df['bathrooms_raw'].apply(extract_bathroom_count)

inventory_df

,unique_id,block_num,unit_count,case_type_name,submission_year,block_address,occupancy_type,occupancy_or_vacancy_date,occupancy_or_vacancy_date_year,bedrooms_raw,bathrooms_raw,square_footage,monthly_rent,base_rent_includes_water,base_rent_includes_natural_gas,base_rent_includes_electricity,base_rent_includes_refuse_recycling,base_rent_includes_other_utilities,past_occupancy,vacancy_date,signature_date,occupancy_or_vacancy_date_history,year_property_built,point,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at,longitude,latitude,min_square_footage,max_square_footage,min_monthly_rent,max_monthly_rent,bedrooms,bathrooms
0,-3628485104392603866,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
1,-2826846618703330734,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/02/08,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$250-$500,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,250.0,500.0,0,0
2,-8535828261092955964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
3,-9003118150577022274,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
4,3838177617614172843,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2023/05/03,2023,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186683,-7484992084690087964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
186684,-6165581344280503108,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/02,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,<NA>,<NA>,0,0
186685,-6469473855511513476,1369,12,Housing Inventory - Unit information (2022),2022,100 Block of 09TH AVE,Vacant,NaN,NaN,One-Bedroom,One bathroom,501-750 Sq.Ft,NaN,N,N,N,N,NaN,NaN,2022/06/21,2022/06/21,NaN,1924.0,POINT (-122.467900457 37.78559791),Inner Richmond,1.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.467900,37.785598,501.0,750.0,<NA>,<NA>,1,1.0
186686,-391686748792554513,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022/01/31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$751-$1000,Y,Y,Y,Y,NaN,No,NaN,2024/02/29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,751.0,1000.0,0,0
186687,-452610934157304139,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaN,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024/01/22,2024/02/29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025/03/14 01:30:37 AM,2025/03/14 06:05:44 AM,-122.394549,37.781408,0.0,250.0,<NA>,<NA>,0,0

In [65]:
date_columns = ['occupancy_or_vacancy_date', 'vacancy_date', 'signature_date', 'data_as_of', 'data_loaded_at', ]

# convert the string date columns to timestamps to be used in parquet
for column in date_columns:
    inventory_df[column] = pandas.to_datetime(inventory_df[column], errors='coerce')

In [66]:
inventory_df.drop(columns=[
    'occupancy_or_vacancy_date_history',
    'point',
    'unique_id',
]).to_parquet(
    'data/sf_rent/rent_board_inventory.parquet',
    index=False,
    engine="pyarrow",
    coerce_timestamps="us",
    allow_truncated_timestamps=True
)

In [67]:
inventory_df

,unique_id,block_num,unit_count,case_type_name,submission_year,block_address,occupancy_type,occupancy_or_vacancy_date,occupancy_or_vacancy_date_year,bedrooms_raw,bathrooms_raw,square_footage,monthly_rent,base_rent_includes_water,base_rent_includes_natural_gas,base_rent_includes_electricity,base_rent_includes_refuse_recycling,base_rent_includes_other_utilities,past_occupancy,vacancy_date,signature_date,occupancy_or_vacancy_date_history,year_property_built,point,analysis_neighborhood,supervisor_district,data_as_of,data_loaded_at,longitude,latitude,min_square_footage,max_square_footage,min_monthly_rent,max_monthly_rent,bedrooms,bathrooms
0,-3628485104392603866,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022-01-31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
1,-2826846618703330734,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022-02-08,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$250-$500,Y,Y,Y,Y,NaN,No,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,250.0,500.0,0,0
2,-8535828261092955964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022-01-31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
3,-9003118150577022274,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022-01-31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,No,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
4,3838177617614172843,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2023-05-03,2023,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186683,-7484992084690087964,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022-01-31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$501-$750,Y,Y,Y,Y,NaN,Yes,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,501.0,750.0,0,0
186684,-6165581344280503108,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaT,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024-01-02,2024-02-29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,<NA>,<NA>,0,0
186685,-6469473855511513476,1369,12,Housing Inventory - Unit information (2022),2022,100 Block of 09TH AVE,Vacant,NaT,NaN,One-Bedroom,One bathroom,501-750 Sq.Ft,NaN,N,N,N,N,NaN,NaN,2022-06-21,2022-06-21,NaN,1924.0,POINT (-122.467900457 37.78559791),Inner Richmond,1.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.467900,37.785598,501.0,750.0,<NA>,<NA>,1,1.0
186686,-391686748792554513,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Occupied by non-owner,2022-01-31,2022,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,$751-$1000,Y,Y,Y,Y,NaN,No,NaT,2024-02-29,NaN,1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,751.0,1000.0,0,0
186687,-452610934157304139,3775,22,Housing Inventory - Unit information (2024),2024,100 Block of SOUTH PARK,Vacant,NaT,NaN,Studio,Shared bathroom facilities with other units,0-250 Sq.Ft,NaN,N,N,N,N,NaN,Yes,2024-01-22,2024-02-29,"[\n {\n ""date_range_type"": ""Occupied"",\n ...",1907.0,POINT (-122.394549329 37.781408195),Financial District/South Beach,6.0,2025-03-14 01:30:37,2025-03-14 06:05:44,-122.394549,37.781408,0.0,250.0,<NA>,<NA>,0,0

In [69]:
print(inventory_df.dtypes)

unique_id                                       int64
block_num                                      object
unit_count                                      int64
case_type_name                                 object
submission_year                                 int64
block_address                                  object
occupancy_type                                 object
occupancy_or_vacancy_date              datetime64[ns]
occupancy_or_vacancy_date_year                 object
bedrooms_raw                                   object
bathrooms_raw                                  object
square_footage                                 object
monthly_rent                                   object
base_rent_includes_water                       object
base_rent_includes_natural_gas                 object
base_rent_includes_electricity                 object
base_rent_includes_refuse_recycling            object
base_rent_includes_other_utilities             object
past_occupancy                                 object
vacancy_date                           datetime64[ns]
signature_date                         datetime64[ns]
occupancy_or_vacancy_date_history              object
year_property_built                           float64
point                                          object
analysis_neighborhood                          object
supervisor_district                           float64
data_as_of                             datetime64[ns]
data_loaded_at                         datetime64[ns]
longitude                                     float64
latitude                                      float64
min_square_footage                             object
max_square_footage                             object
min_monthly_rent                               object
max_monthly_rent                               object
bedrooms                                       object
bathrooms                                      object
dtype: object